<a href="https://colab.research.google.com/github/kmbarb/data_2_checks/blob/main/kc_2.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [24]:
import pandas as pd
import numpy as np

I am importing the Public Library Income Per Capita csv from the California State Library's webpage, and displaying the first five columns.

In [25]:
df = pd.read_csv('https://www.library.ca.gov/wp-content/uploads/2022/11/LIPC-FY2021.csv?2022-10-12')

In [26]:
print(df.shape)
df.head()

(186, 4)

,Unnamed: 0,Unnamed: 1,Unnamed: 2,Unnamed: 3
0,Location,2.1 Population of The Legal Service Area,3.1 Local Government Income,Local Income per Capita
1,A. K. SMILEY PUBLIC LIBRARY,"72,585","$2,619,509",$36.09
2,ALAMEDA COUNTY LIBRARY,"588,941","$33,664,887",$57.16
3,ALAMEDA FREE LIBRARY,"77,784","$5,431,323",$69.83
4,ALHAMBRA CIVIC CENTER LIBRARY,"81,834","$2,803,207",$34.25

The column names are in the first row rather than the header, and they could be renamed for easier use in python. First I will rename the columns.

In [27]:
fixed_columns = {
    'Unnamed: 0' : 'location',
    'Unnamed: 1' : 'population',
    'Unnamed: 2' : 'local_government_income',
    'Unnamed: 3' : 'local_income_per_capita'
}

df.rename(columns=fixed_columns, inplace=True)
df.columns

Index(['location', 'population', 'local_government_income',
       'local_income_per_capita'],
      dtype='object')

In [28]:
print(df.shape)
df.head()

(186, 4)

,location,population,local_government_income,local_income_per_capita
0,Location,2.1 Population of The Legal Service Area,3.1 Local Government Income,Local Income per Capita
1,A. K. SMILEY PUBLIC LIBRARY,"72,585","$2,619,509",$36.09
2,ALAMEDA COUNTY LIBRARY,"588,941","$33,664,887",$57.16
3,ALAMEDA FREE LIBRARY,"77,784","$5,431,323",$69.83
4,ALHAMBRA CIVIC CENTER LIBRARY,"81,834","$2,803,207",$34.25

The old names were still in the first row of the dataset, so I will use iloc to remove the first row.

In [30]:
df = df.iloc[1:]
print(df)

                           location population local_government_income  \
1       A. K. SMILEY PUBLIC LIBRARY     72,585              $2,619,509
2            ALAMEDA COUNTY LIBRARY    588,941             $33,664,887
3              ALAMEDA FREE LIBRARY     77,784              $5,431,323
4     ALHAMBRA CIVIC CENTER LIBRARY     81,834              $2,803,207
5    ALPINE COUNTY LIBRARY/ARCHIVES      1,200                $333,334
..                              ...        ...                     ...
181          WILLOWS PUBLIC LIBRARY     13,455                $333,880
182         WOODLAND PUBLIC LIBRARY     60,137              $2,191,946
183             YOLO COUNTY LIBRARY    161,028              $8,584,928
184      YORBA LINDA PUBLIC LIBRARY     67,233              $6,328,688
185             YUBA COUNTY LIBRARY     82,275                $963,266

    local_income_per_capita
1                    $36.09
2                    $57.16
3                    $69.83
4                    $34.25
5                   $277.78
..                      ...
181                  $24.81
182                  $36.45
183                  $53.31
184                  $94.13
185                  $11.71

[185 rows x 4 columns]